/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "uart_sameboard.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP) && 0
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

UARTHandle_t hUART1;
UARTHandle_t hUART2;
uint8_t pTxBuffer1[10];
uint8_t pRxBuffer1[10];
uint8_t pTxBuffer2[10];
uint8_t pRxBuffer2[10];


int main(void)
{
    /** Define handle for UART1 */
	hUART1.pRCC = RCC;
	hUART1.pGPIO = GPIOA;
	hUART1.pUART = USART1;
	hUART1.GPIO_bus = AHB1;
	hUART1.UART_bus = APB2;
	hUART1.Clk_pin = 4;
	hUART1.TX_pin = 9;
	hUART1.RX_pin = 10;
	hUART1.oversampling = OVR16;
	hUART1.word_length = EIGHT_BIT;
	hUART1.parity_enable = FALSE;
	hUART1.transmit_interrupt = FALSE;
	hUART1.receiver_interrupt = TRUE;
	hUART1.interrupt_enable = TRUE;
	hUART1.interrupt_number = 37;
	hUART1.pTxBuffer = pTxBuffer1;
	hUART1.pRxBuffer = pRxBuffer1;
	hUART1.RxIndex = 0;
	hUART1.baud_rate = BAUD_9600;
	hUART1.to_transmit = TRUE;
	hUART1.to_receive = TRUE;
	hUART1.enable = TRUE;

    /** Define handle for UART2 */
	hUART2.pRCC = RCC;
	hUART2.pGPIO = GPIOA;
	hUART2.pUART = USART2;
	hUART2.GPIO_bus = AHB1;
	hUART2.UART_bus = APB1;
	hUART2.Clk_pin = 17;
	hUART2.TX_pin = 2;
	hUART2.RX_pin = 3;
	hUART2.oversampling = OVR16;
	hUART2.word_length = EIGHT_BIT;
	hUART2.parity_enable = FALSE;
	hUART2.transmit_interrupt = FALSE;
	hUART2.receiver_interrupt = TRUE;
	hUART2.interrupt_enable = TRUE;
	hUART2.interrupt_number = 38;
	hUART2.pTxBuffer = pTxBuffer2;
	hUART2.pRxBuffer = pRxBuffer2;
	hUART2.RxIndex = 0;
	hUART2.baud_rate = BAUD_9600;
	hUART2.to_transmit = TRUE;
	hUART2.to_receive = TRUE;
	hUART2.enable = TRUE;
	/** Initial configuration of UART1 */
	UART_Init(&hUART1);
	/** Initial configuration of UART2 */
	UART_Init(&hUART2);

	/** Loop forever */
	for(;;){
//		while(!(hUART1.pUART->SR >> 7));	/** Wait for the transmit buffer to be empty */
//		hUART1.pUART->DR = ++hUART1.pRxBuffer[hUART1.RxIndex];
//		while(!(hUART2.pUART->SR >> 7));	/** Wait for the transmit buffer to be empty */
//		hUART2.pUART->DR = ++hUART2.pRxBuffer[hUART2.RxIndex];
	}
}
