Functions
void GPIO_Init(GPIO_Handle_t *pGPIOHandle, uint8_t pin)
Initialize the I2C peripheral module based on the SCLK frequency, Device address (if it is a slave), Acknowledgement enable, and Fast Mode Duty Cycle.
I2C_Handle_t * Pointer to instance of class I2C_Handle_t None
References GPIO_ConfigureAlternateFunction, GPIO_ConfigureMode, GPIO_ConfigurePullUpDown, GPIO_Handle_t::GPIO_PinConfig, GPIO_PinConfig_t::Mode, GPIO_Handle_t::pGPIOx, RCC_AHBClockEnable.
void GPIO_DeInit(GPIO_Handle_t *pGPIOHandle)
De-initialize the I2C peripheral module.
I2C_Handle_t * Pointer to instance of class I2C_Handle_t None
void GPIO_ConfigureMode(GPIO_Handle_t *pGPIOHandle, uint8_t pin)
Transmit the data byte to the slave.
pI2CHandle Pointer to the master I2C instance of class I2C_Handle_t pSlaveAddress Pointer to the slave address pData Pointer to the data byte to be sent None
References GPIO_Handle_t::GPIO_PinConfig, GPIO_PinConfig_t::Mode, GPIO_Handle_t::pGPIOx.
Referenced by GPIO_Init.
void GPIO_ConfigureOutputType(GPIO_Handle_t *pGPIOHandle, uint8_t pin)
References GPIO_Handle_t::GPIO_PinConfig, GPIO_PinConfig_t::OType, GPIO_Handle_t::pGPIOx.
void GPIO_ConfigureOutputSpeed(GPIO_Handle_t *pGPIOHandle, uint8_t pin)
References GPIO_Handle_t::GPIO_PinConfig, GPIO_PinConfig_t::OutputSpeed, GPIO_Handle_t::pGPIOx.
void GPIO_ConfigurePullUpDown(GPIO_Handle_t *pGPIOHandle, uint8_t pin)
References GPIO_Handle_t::GPIO_PinConfig, GPIO_Handle_t::pGPIOx, GPIO_PinConfig_t::PullUpDown.
Referenced by GPIO_Init.
void GPIO_ConfigureAlternateFunction(GPIO_Handle_t *pGPIOHandle, uint8_t pin)
References GPIO_PinConfig_t::AlternateFunction, GPIO_Handle_t::GPIO_PinConfig, GPIO_Handle_t::pGPIOx.
Referenced by GPIO_Init.
void GPIO_Set_Bit(GPIO_Handle_t *pGPIOHandle, uint8_t pin)
void GPIO_Clear_Bit(GPIO_Handle_t *pGPIOHandle, uint8_t pin)
Receive the data byte from the slave.
pI2CHandle Pointer to the master I2C instance of class I2C_Handle_t pSlaveAddress Pointer to the slave address pReceive Pointer to the data byte where the data to receive None
uint8_t GPIO_Get_BitValue(GPIO_Handle_t *pGPIOHandle)
Transmit the data byte to the master.
pI2CHandle Pointer to the slave I2C instance of class I2C_Handle_t pData Pointer to the data byte to be sent None
void I2C_Init(I2C_Handle_t *)
Initialize the I2C peripheral module based on the SCLK frequency, Device address (if it is a slave), Acknowledgement enable, and Fast Mode Duty Cycle.
I2C_Handle_t * Pointer to instance of class I2C_Handle_t None
void I2C_DeInit(I2C_Handle_t *)
De-initialize the I2C peripheral module.
I2C_Handle_t * Pointer to instance of class I2C_Handle_t None
void I2C_MasterSendData(I2C_Handle_t *pI2CHandle, const uint8_t *pSlaveAddress, uint8_t *pData)
Transmit the data byte to the slave.
pI2CHandle Pointer to the master I2C instance of class I2C_Handle_t pSlaveAddress Pointer to the slave address pData Pointer to the data byte to be sent None
void I2C_MasterReceiveData(I2C_Handle_t *pI2CHandle, const uint8_t *pSlaveAddress, uint8_t *pReceive)
Receive the data byte from the slave.
pI2CHandle Pointer to the master I2C instance of class I2C_Handle_t pSlaveAddress Pointer to the slave address pReceive Pointer to the data byte where the data to receive None
void I2C_SlaveSendData(I2C_Handle_t *pI2CHandle, uint8_t *pData)
Transmit the data byte to the master.
pI2CHandle Pointer to the slave I2C instance of class I2C_Handle_t pData Pointer to the data byte to be sent None
void I2C_SlaveReceiveData(I2C_Handle_t *pI2CHandle, uint8_t *pReceive)
Receive the data byte from the master.
pI2CHandle Pointer to the slave I2C instance of class I2C_Handle_t pReceive Pointer to the data byte where the data to receive None
void I2C_Error_Interrupt_Handler(I2C_Handle_t *pI2CHandle)
Callback function for I2C Error Interrupt handler.
pI2CHandle Pointer to the slave/master I2C instance of class I2C_Handle_t None
void I2C_Event_Interrupt_Handler(I2C_Handle_t *pI2CHandle)
Callback function for I2C Event Interrupt handler.
pI2CHandle Pointer to the slave/master I2C instance of class I2C_Handle_t None
void RCC_EnableClock(RCC_Handle_t *pRCC, uint8_t pos)
References RCC_Config_t::bus, RCC_Handle_t::pRCC, RCC_Handle_t::RCC_Config.
void RCC_ResetClock(RCC_Handle_t *pRCC, uint8_t pos)
References RCC_Config_t::bus, RCC_Handle_t::pRCC, RCC_Handle_t::RCC_Config.
void RCC_SetPrescaler(RCC_Handle_t *pRCC, uint8_t scaler)
References AHB1, AHB2, AHB3, APB1, RCC_Config_t::bus, RCC_Handle_t::pRCC, RCC_Handle_t::RCC_Config.
ClockSrc_t RCC_GetSystemClock()
uint8_t RCC_GetPrescaler(RCC_Handle_t *pRCC)
References AHB1, AHB2, AHB3, APB1, RCC_Config_t::bus, RCC_Handle_t::pRCC, RCC_Handle_t::RCC_Config.