/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

#define DELAY			(1*30)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int32_t input = 5;
double output_k_1 = 0;
double output_k_2 = 0;
double output = 0;
uint32_t samples = DELAY;

int main(void)
{
    /* Loop forever */
	/* Enable FPU */
	SCB->CPACR &= ~(0xF << 20);
	SCB->CPACR |= (0xF << 20);

	RCC->CFGR |= (0xD << 4);
	RCC->AHB1ENR |= 0x1;
	GPIOA->MODER &= ~0x3;
	GPIOA->MODER |= 0x1;
	for(;;){
		GPIOA->ODR ^= 0x1;
//		input = (GPIOA->ODR) * 5;
		input *= -1;
		output = 0.0, output_k_1 = 0.0, output_k_2 = 0.0;
//		output_k_2 = output_k_1;
//		output_k_1 = output;
		for(int i = 0; i < samples; i++){
			output = 1.1*output_k_1 - 0.3*output_k_2 + (0.2*(double)input);
			output_k_2 = output_k_1;
			output_k_1 = output;
		}
	}
}
